# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder stage
FROM node:lts-alpine as builder
WORKDIR /app

# Install all dependencies (including dev) without running prepare
COPY package.json package-lock.json tsconfig.json ./
RUN npm install --ignore-scripts

# Copy source and build
COPY src ./src
RUN npm run build

# Final stage
FROM node:lts-alpine
WORKDIR /app

# Copy build output and dependencies from builder
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY package.json ./package.json

# Expose no ports since stdio
ENTRYPOINT ["node", "build/index.js"]
